# Generated by Django 6.0.4 on 2026-08-20 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='events.attendee'),
        ),
        migrations.AddField(
            model_name='job',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='events.event'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['event', 'status'], name='jobs_job_event_i_492d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['attendee', 'status'], name='jobs_job_attende_fd88d9_idx'),
        ),
    ]
