# Generated by Django 6.0.4 on 2026-08-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_attendee_job_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='kit_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
