# Generated by Django 6.0.4 on 2026-04-30 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaintSet',
            fields=[
                ('id', models.SlugField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('paint_type', models.CharField(max_length=50)),
                ('tube_count', models.IntegerField()),
            ],
            options={
                'ordering': ['paint_type', 'tube_count', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaintColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('hex', models.CharField(max_length=7)),
                ('paint_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='palettes.paintset')),
            ],
            options={
                'order_with_respect_to': 'paint_set',
            },
        ),
    ]
