# Generated by Django 6.0.4 on 2026-04-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palettes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintset',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
