# Generated by Django 6.0.4 on 2026-08-20 14:17

import django.db.models.deletion
import events.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('public_token', models.CharField(default=events.models.generate_event_token, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], db_index=True, default='active', max_length=12)),
                ('otp_required', models.BooleanField(default=False)),
                ('max_kits_per_attendee', models.PositiveIntegerField(default=1)),
                ('branding', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default='active', max_length=12)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.organizerprofile'),
        ),
        migrations.CreateModel(
            name='CreditReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('consumed', 'Consumed'), ('released', 'Released')], default='reserved', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='events.attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='events.event')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='events.organizerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CreditLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('grant', 'Grant'), ('allocation', 'Allocation'), ('adjustment', 'Adjustment'), ('reservation', 'Reservation'), ('consumption', 'Consumption'), ('release', 'Release')], max_length=16)),
                ('quantity', models.IntegerField()),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_entries', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='events.event')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='events.organizerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='attendee',
            constraint=models.UniqueConstraint(fields=('event', 'phone_number'), name='unique_attendee_phone_per_event'),
        ),
        migrations.AddIndex(
            model_name='creditreservation',
            index=models.Index(fields=['event', 'status'], name='events_cred_event_i_8093ef_idx'),
        ),
        migrations.AddIndex(
            model_name='creditreservation',
            index=models.Index(fields=['attendee', 'status'], name='events_cred_attende_5d09f0_idx'),
        ),
        migrations.AddIndex(
            model_name='creditledgerentry',
            index=models.Index(fields=['organizer', 'entry_type'], name='events_cred_organiz_af21db_idx'),
        ),
        migrations.AddIndex(
            model_name='creditledgerentry',
            index=models.Index(fields=['event', 'entry_type'], name='events_cred_event_i_f9fbe5_idx'),
        ),
    ]
