<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { createOrganizerEvent } from '../api/events.js'
const router = useRouter(); const name = ref(''); const eventDate = ref(''); const allocatedCredits = ref(1); const maxKits = ref(1); const otpRequired = ref(false); const errorMessage = ref(''); const submitting = ref(false)
async function submit() { submitting.value = true; errorMessage.value = ''; try { const event = await createOrganizerEvent({ name: name.value, event_date: eventDate.value, allocated_credits: allocatedCredits.value, max_kits_per_attendee: maxKits.value, otp_required: otpRequired.value, branding: {} }); router.push({ name: 'organizer-event', params: { eventId: event.id } }) } catch (error) { errorMessage.value = error.data?.detail ?? 'Could not create this event.' } finally { submitting.value = false } }
</script>
<template><section class="create-page"><form class="create-form" @submit.prevent="submit"><RouterLink class="back-link" to="/organizer">← Dashboard</RouterLink><p class="eyebrow">NEW EVENT</p><h1>Set the scene.</h1><label>Event name<input v-model="name" required placeholder="Saturday paint club" /></label><label>Event date<input v-model="eventDate" type="date" required /></label><div class="form-grid"><label>Credits<input v-model.number="allocatedCredits" type="number" min="1" required /></label><label>Kits per attendee<input v-model.number="maxKits" type="number" min="1" required /></label></div><label class="check-row"><input v-model="otpRequired" type="checkbox" /> Require phone verification</label><p v-if="errorMessage" class="form-error">{{ errorMessage }}</p><button class="primary-button" :disabled="submitting">{{ submitting ? 'Creating...' : 'Create event' }}</button></form></section></template>
<style scoped>
.create-page { min-height: calc(100dvh - 80px); display: grid; place-items: center; padding: var(--space-xl) var(--space-md); }.create-form { width: min(620px, 100%); display: grid; gap: var(--space-sm); padding: clamp(28px, 6vw, 64px); background: var(--color-snow); color: var(--color-bg); border: var(--border-sticker-lime); box-shadow: var(--shadow-sticker-lg); }.back-link { color: var(--color-midnight); font-weight: var(--weight-bold); margin-bottom: var(--space-lg); }.eyebrow { color: var(--color-midnight); font-size: var(--text-sm); font-weight: var(--weight-bold); letter-spacing: .12em; }.create-form h1 { color: var(--color-midnight); font-size: clamp(2.8rem, 8vw, 4.8rem); margin-bottom: var(--space-lg); }label { display: grid; gap: var(--space-xs); margin-top: var(--space-sm); font-weight: var(--weight-bold); }input { min-height: 48px; padding: 0 var(--space-sm); border: 3px solid var(--color-midnight); border-radius: var(--radius-sm); font-size: var(--text-body); }.form-grid { display: grid; grid-template-columns: 1fr 1fr; gap: var(--space-md); }.check-row { display: flex; align-items: center; gap: var(--space-sm); }.check-row input { width: 20px; min-height: 20px; }.primary-button { min-height: 54px; margin-top: var(--space-lg); background: var(--color-indigo); color: var(--color-snow); border: var(--border-sticker-bg); box-shadow: var(--shadow-sticker-sm); border-radius: var(--radius-button); font-weight: var(--weight-extrabold); font-size: var(--text-body); }.form-error { color: #b42318; }@media (max-width: 520px) { .form-grid { grid-template-columns: 1fr; } }
</style>