<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/authStore.js'
const router = useRouter(); const auth = useAuthStore(); const firstName = ref(''); const email = ref(''); const password = ref(''); const errorMessage = ref('')
async function submit() { errorMessage.value = ''; try { await auth.signUp({ first_name: firstName.value, email: email.value, password: password.value }); router.push({ name: 'organizer-home' }) } catch (error) { errorMessage.value = error.data?.email?.[0] ?? error.data?.detail ?? 'Could not create the account.' } }
</script>
<template><section class="auth-page"><form class="auth-form" @submit.prevent="submit"><p class="eyebrow">HOST YOUR EVENT</p><h1>Make it yours.</h1><label>Name<input v-model="firstName" type="text" autocomplete="given-name" /></label><label>Email<input v-model="email" type="email" autocomplete="email" required /></label><label>Password<input v-model="password" type="password" autocomplete="new-password" minlength="8" required /></label><p v-if="errorMessage" class="form-error">{{ errorMessage }}</p><button class="primary-button" :disabled="auth.loading">{{ auth.loading ? 'Creating...' : 'Create organizer account' }}</button><p class="auth-form__switch">Already have an account? <RouterLink to="/login">Sign in</RouterLink></p></form></section></template>
<style scoped>
.auth-page { min-height: calc(100dvh - 80px); display: grid; place-items: center; padding: var(--space-xl) var(--space-md); }.auth-form { display: grid; gap: var(--space-sm); width: min(460px, 100%); padding: clamp(28px, 6vw, 56px); background: var(--color-snow); color: var(--color-bg); border: var(--border-sticker-lime); box-shadow: var(--shadow-sticker-lg); }.eyebrow { color: var(--color-midnight); font-size: var(--text-sm); font-weight: var(--weight-bold); letter-spacing: .12em; }.auth-form h1 { color: var(--color-midnight); font-size: clamp(2.5rem, 7vw, 4rem); margin-bottom: var(--space-lg); }label { display: grid; gap: var(--space-xs); margin-top: var(--space-sm); font-weight: var(--weight-bold); }input { min-height: 48px; padding: 0 var(--space-sm); border: 3px solid var(--color-midnight); border-radius: var(--radius-sm); font-size: var(--text-body); }.primary-button { min-height: 52px; margin-top: var(--space-md); background: var(--color-indigo); color: var(--color-snow); border: var(--border-sticker-bg); box-shadow: var(--shadow-sticker-sm); border-radius: var(--radius-button); font-weight: var(--weight-extrabold); font-size: var(--text-body); }.form-error { color: #b42318; }.auth-form__switch { margin-top: var(--space-md); }.auth-form__switch a { color: var(--color-midnight); font-weight: var(--weight-bold); text-decoration: underline; }
</style>