release: python manage.py migrate --noinput && python manage.py collectstatic --noinput
web: gunicorn paintober_backend.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --timeout 120
worker: python manage.py run_scheduler
